services:
  api-service:
    image: rohitshah1706/spe_api_service:latest
    container_name: api-service
    ports:
      - "3000:3000"
    environment:
      LOGS_PATH: "/logs"
    volumes:
      - ./logs:/logs